[package]
name = "hbw"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
console = "0.15.8"
anyhow = "1.0.86"
yew-router = "0.18.0"
